'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const [root,compiler,censusFile,output]=process.argv.slice(2),ts=require(compiler),sources=[];
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function read(name){sources.push({path:name,sha256:hash(path.join(root,name))});return ts.createSourceFile(name,fs.readFileSync(path.join(root,name),'utf8'),ts.ScriptTarget.Latest,true);}
function variable(ast,name){for(const s of ast.statements)if(ts.isVariableStatement(s))for(const d of s.declarationList.declarations)if(d.name.getText(ast)===name)return d.initializer;throw Error(name);}
function stringArray(node){assert(ts.isArrayLiteralExpression(node));return node.elements.map(x=>{assert(ts.isStringLiteral(x));return x.text;});}
const provider=read('packages/data-provider/src/schemas.ts');
function zodFields(name){const node=variable(provider,name);assert(ts.isCallExpression(node)&&node.expression.getText(provider)==='z.object');const obj=node.arguments[0];assert(ts.isObjectLiteralExpression(obj));return obj.properties.map(p=>{assert(ts.isPropertyAssignment(p));return {name:p.name.getText(provider),definition:p.initializer.getText(provider),line:provider.getLineAndCharacterOfPosition(p.getStart(provider)).line+1};});}
const message=read('packages/data-schemas/src/methods/message.ts'),selection=variable(message,'CLIENT_MESSAGE_SELECT');
assert(ts.isCallExpression(selection)&&ts.isPropertyAccessExpression(selection.expression)&&selection.expression.name.text==='join');
const exclusions=stringArray(selection.expression.expression).map(x=>{assert(x.startsWith('-'));return x.slice(1);});
const config=read('packages/data-provider/src/config.ts');const keys=variable(config,'excludedKeys');assert(ts.isNewExpression(keys)&&keys.expression.getText(config)==='Set');const excludedKeys=stringArray(keys.arguments[0]);
const extraMessage=provider.statements.find(s=>ts.isTypeAliasDeclaration(s)&&s.name.text==='TMessage');assert(ts.isIntersectionTypeNode(extraMessage.type));const literal=extraMessage.type.types.find(ts.isTypeLiteralNode);assert(literal);const extensions=literal.members.map(x=>x.name.getText(provider));
const census=JSON.parse(fs.readFileSync(censusFile,'utf8'));
for(const file of ['api/app/clients/BaseClient.js','api/server/routes/messages.js','api/server/middleware/messageValidation.js','packages/api/src/middleware/messageValidation.ts','packages/api/src/conversations/save.ts','packages/data-schemas/src/methods/conversation.ts','api/server/controllers/agents/client.js','packages/api/src/agents/hitl/answers.ts','packages/data-schemas/src/models/plugins/tenantIsolation.ts','packages/data-schemas/package.json','packages/data-schemas/tsdown.config.mjs','api/models/index.js'])read(file);
const records=census.records.map((record,i)=>{
 const p=zodFields(i===0?'tMessageSchema':'tConversationSchema');const map=new Map(p.map(x=>[x.name,x]));
 const fields=record.fields.map(f=>({name:f.name,source:{file:f.file,line:f.line},storageDefinition:f.definition,interfaceType:record.members.find(m=>m.name===f.name)?.type??null,provider:map.get(f.name)??null,defaultRead:f.flags.select==='false'?'hidden':'included',portableServerRead:f.flags.select==='false'?'not fetched by default':f.name==='messages'&&i===1?'omit physical relationship array':'preserve field and presence',publicRead:i===1?'not in pilot public conversation scope':f.flags.select==='false'?'hidden by schema':exclusions.includes(f.name)?'excluded':exclusions.some(x=>x.startsWith(f.name+'.'))?'included with nested exclusions':'included',endpointUnsetRule:i===0?null:excludedKeys.includes(f.name)?(['spec','iconURL'].includes(f.name)?'kept-key exception: undefined may unset':f.name==='model'?'protected only when agent-owned':'excluded from unset enumeration'):'undefined option may unset existing key'}));
 return {name:record.schemaName,fields,providerOnly:p.filter(x=>!record.fields.some(f=>f.name===x.name)).map(x=>x.name),interfaceOnly:record.interfaceOnly,implicit:{createdAt:'timestamp; preserve Date locally and string at HTTP serialization',updatedAt:'timestamp; preserve Date locally and string at HTTP serialization',_id:'adapter-private; omit from portable record',__v:'adapter-private; omit from portable record'}};
});
const result={sourceHead:require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),sources,census:{path:censusFile,sha256:hash(censusFile)},exclusions,excludedKeys,messageProviderExtensions:extensions,records,limits:'Static declared/default projection rules; no runtime Mongoose selection/casting or historical Mixed-value validation. Provider-only fields are not automatically persistence requirements.'};
fs.writeFileSync(output,JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({fields:records.map(r=>r.fields.length),exclusions:exclusions.length,nestedExclusions:exclusions.filter(x=>x.includes('.')).length,publicMessageFields:records[0].fields.filter(f=>f.publicRead.startsWith('included')).length,providerOnly:records.map(r=>r.providerOnly),messageProviderExtensions:extensions},null,2));
